//! Shared types used across application for Executable
//!
//! All reference these instead of defining their own copies.

use serde::{Deserialize, Serialize};

/// HTTP version to use for the request.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "PascalCase")]
pub enum HttpVersion {
    #[default]
    Auto,
    Http1,
    Http2,
}

/// HTTP methods supported by Beep
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum HttpMethod {
    Get,
    Post,
    Put,
    Delete,
    Patch,
    Head,
    Options,
    Other(String),
}

impl HttpMethod {
    pub fn as_str(&self) -> &str {
        match self {
            HttpMethod::Get => "GET",
            HttpMethod::Post => "POST",
            HttpMethod::Put => "PUT",
            HttpMethod::Delete => "DELETE",
            HttpMethod::Patch => "PATCH",
            HttpMethod::Head => "HEAD",
            HttpMethod::Options => "OPTIONS",
            HttpMethod::Other(method) => method,
        }
    }

    pub fn to_http_method(&self) -> http::Method {
        match self {
            HttpMethod::Get => http::Method::GET,
            HttpMethod::Post => http::Method::POST,
            HttpMethod::Put => http::Method::PUT,
            HttpMethod::Delete => http::Method::DELETE,
            HttpMethod::Patch => http::Method::PATCH,
            HttpMethod::Head => http::Method::HEAD,
            HttpMethod::Options => http::Method::OPTIONS,
            HttpMethod::Other(method) => {
                http::Method::from_bytes(method.as_bytes()).unwrap_or(http::Method::GET)
            }
        }
    }
}

impl Default for HttpMethod {
    fn default() -> Self {
        HttpMethod::Get
    }
}

impl std::fmt::Display for HttpMethod {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

/// Authentication types known by Beep.
///
/// The `Custom` variant captures any other scheme.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Auth {
    None,
    Basic { username: String, password: String },
    Bearer { token: String },
    Custom { value: String },
}

impl Default for Auth {
    fn default() -> Self {
        Auth::None
    }
}

fn default_enabled() -> bool {
    true
}

/// A single header field.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct HeaderField {
    pub key: String,
    pub value: String,
    #[serde(default = "default_enabled")]
    pub enabled: bool,
    /// Whether this header was auto-generated by the app.
    #[serde(default)]
    pub auto: bool,
}

/// A single query parameter field (without source-level metadata).
///
/// For parser-level `is_inline` tracking, see `http_parser::ParsedQueryField`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QueryField {
    pub key: String,
    pub value: String,
    #[serde(default = "default_enabled")]
    pub enabled: bool,
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // -----------------------------------------------------------------------
    // HttpMethod
    // -----------------------------------------------------------------------

    #[test]
    fn test_http_method_display() {
        assert_eq!(HttpMethod::default().to_string(), "GET");
        assert_eq!(HttpMethod::Get.as_str(), "GET");
        assert_eq!(HttpMethod::Post.to_string(), "POST");
        assert_eq!(HttpMethod::Put.to_string(), "PUT");
        assert_eq!(HttpMethod::Delete.to_string(), "DELETE");
        assert_eq!(HttpMethod::Patch.to_string(), "PATCH");
        assert_eq!(HttpMethod::Head.to_string(), "HEAD");
        assert_eq!(HttpMethod::Options.to_string(), "OPTIONS");
    }

    // -----------------------------------------------------------------------
    // HeaderField
    // -----------------------------------------------------------------------

    #[test]
    fn test_header_field_default_auto() {
        let h = HeaderField {
            key: "Accept".into(),
            value: "*/*".into(),
            enabled: true,
            auto: false,
        };
        let json = serde_json::to_string(&h).unwrap();
        let parsed: HeaderField = serde_json::from_str(&json).unwrap();
        assert!(!parsed.auto);
        assert!(parsed.enabled);
    }
}
